### PR TITLE
Fix abstract méthods

### PR DESCRIPTION
**Pull request by kmiladi**
Define search and buildQuery methods as abstract

### CODE REVIEW

**Comment by ghaliano** [comment]
Hi, thanks a lot for this help
however there are already an interface called MediaProviderInterface containing some of your logic
<?php

namespace MediaGateway;

interface MediaProviderInterface
{
    /**
     \* @param  Query $query
     \* @return array
     */
    public function search(Query $query);

**Comment by kmiladi** [comment]
Ah you are right, but buildQuery is not defined on this interface

**Comment by ghaliano** [comment]
Yes, 

but the query building is the business of the provider it self :)

in general, maybe some other provider don't need it but should implement the search method to perform that future

**Comment by kmiladi** [comment]
OK

**Pull request closed without merging**
